# Generated by Django 5.0.3 on 2024-08-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
