# Generated by Django 5.0.3 on 2024-08-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subscribers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Subscribers'},
        ),
    ]
